### ISSUE TITLE
python [Errno 24] Too many open files

### ISSUE THREAD

**Issue by FreifunkUFO** [freifunk/meshkit#24]
Nach ein paar Tagen bringt meshkit öfters folgenden fehler.
(workaround ist das stoppen und -9-killen der python prozesse

```
DEBUG:__restricted__: result: null
Traceback (most recent call last):
File "/home/walter/meshkit/web2py/gluon/shell.py", line 271, in run
File "<string>", line 1, in <module>
File "/home/walter/meshkit/web2py/gluon/scheduler.py", line 730, in loop
File "/home/walter/meshkit/web2py/gluon/scheduler.py", line 354, in async
File "/usr/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
File "/usr/lib/python2.7/multiprocessing/queues.py", line 63, in init
File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in init
File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in init
OSError: [Errno 24] Too many open files

```

**Comment by FreifunkUFO** [comment]
das passiert im screen-fenster, wo folgendes laeuft:

 python web2py.py -M -K meshkit

**Comment by FreifunkUFO** [comment]
laut https://plan.leipzig.freifunk.net/issues/505#change-2153 mal probieren, das ulimit zu erhöhen...
